### ISSUE TITLE
Support for UE4.26

### ISSUE THREAD

**Issue by Extremys** [stereolabs/zed-unreal-plugin#10]
Trying to build with official UE4.26 tag, but not supported. IT would be great to patch the repo, thx a lot. :) 
It would be also great to distribute plugin binaries.

**Comment by Tetsujinfr** [comment]
I agree with @Extremys , would be great to have some love from stereolabs with the unreal plugin.
Any plan to support a proper plugin? Or at least have the latest 4.26 supported?
Thanks
