### ISSUE TITLE
Unable to instantiate module Stereolabs

### ISSUE THREAD

**Issue by TheGreySam** [stereolabs/zed-unreal-plugin#15]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

![imagen](https://user-images.githubusercontent.com/53100726/136619748-5d2f51fc-531a-416a-a9a5-336c06e6e9f1.png)

I succesfully build the UE.4.21-ZED engine and created a project in c++, according to the documentation I had to create a Plugins folder in the new project and paste the Stereolabs UE plugin inside. So I opened Visual Studio 17 again to press Ctrl+F5 and an alert popped in saying if I should compile from a previous version, then another one said that all the components of the stereolabs plugin needed to be rebuilt, I pressed yes and it failed. The terminal says that it was unable to instantiate Stereolabs module.

### Steps to Reproduce

1. build the UE.4.21-ZED engine
2. created a project in c++
3. create a Plugins folder in the new project folder and paste the Stereolabs UE plugin inside
4. opened Visual Studio 17 again to pressed Ctrl+F5 
...

### Expected Result

Project build with the stereolabs plugin

### Actual Result

UnrealBuildTool : error : Unable to instantiate module 'Stereolabs' : ZED SDK Minor Version mismatch : found 5 expected 0
error MSB3075

### ZED Camera model

ZED

### Environment

```shell
Os: Windows 10
CPU:Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.81 GHz
GPU:
ZED sdk version v3.5.3
```

**Comment by Bvallon-sl** [comment]
Hi,

I think there is a version missmatch here. You are using the ZED SDK 3.5 but the UE plugin for 3.0.
Can you please try again with [this](https://github.com/stereolabs/zed-unreal-plugin/tree/UE4.21_ZedSdk3.5) branch instead ?

Best regards,
Benjamin Vallon

**Comment by TheGreySam** [comment]
Yess, now it works

Thanks a lot

**Comment by rosehzero** [comment]
In my case, 
Enviroment is "
Cuda 11.1v ( Cause of GTX 3050)
Zed SDK 3.5.6v ( Cause of Cuda version that only can activated in my graphic cards) 
Zed-unreal-plugin-UE4.21_ZedSdk3.5 "(Cause 

So it seems like All versions are being capatible
But I am still facing error " Unable to instantiate module 'Stereolabs': ZED SDK Minor Version mismatch : found 5 expected 0	ZEDproject "
