### ISSUE TITLE
UE4 crashed，FMallocBinned2 Attempt to realloc an unrecognized block

### ISSUE THREAD

**Issue by GR90** [stereolabs/zed-unreal-plugin#8]
I used Ue4_4.21_zed,and sdk2.7,the project normal running.  I update sdk to 3.0or3.1 this week ,I can't package the project,
![2q](https://user-images.githubusercontent.com/19780276/88904650-ebff0c80-d287-11ea-963a-432893f28d87.png)

once i package this project sucessfully,when i close the .exe,show a window like this:

![1595920385(1)](https://user-images.githubusercontent.com/19780276/88905257-aabb2c80-d288-11ea-96e4-0c2540bdd3c9.png)

**Comment by TheGreySam** [comment]
I'm having the same issue
